### ISSUE TITLE
插件已失效

### ISSUE THREAD

**Issue by cyenxchen** [fanhexin/SaveToBaidu#2]
首先感谢作者。
其次，我是今天刚下载的这个插件，发现无法离线任何链接。
如果作者还在记得这个插件能否更新一下呢？

**Comment by fanhexin** [comment]
多谢反馈，我抽空看一下怎么回事，可能百度网盘那边更新了什么东西。

**Comment by cyenxchen** [comment]
@fanhexin THKS。

**Comment by fanhexin** [comment]
@CyshallChan 我发现百度云盘离线下载现在新建“链接任务”的时候就会报404错误，好像相关url无法访问了，我插件就是用这个url的。如果百度云的前端都出这种问题，我也没办法修复了。你可以登录下百度云，看看你那是不是也有这个问题。

**Comment by cyenxchen** [comment]
我这边没有任何问题阿。
![image](https://user-images.githubusercontent.com/22564041/41816783-2aad1f46-77c0-11e8-9e69-e7cee5e4c18d.png)

**Comment by fanhexin** [comment]
我自己又试了一下确实没问题了，然后再试下插件也没问题了。我什么都没改，你试一下插件，如果没问题那就是百度那边不知道出啥毛病了。

**Comment by cyenxchen** [comment]
@fanhexin 
看图，难道是我的使用方法有误么？
![default](https://user-images.githubusercontent.com/22564041/41818186-f82a2976-77db-11e8-91c7-18e0b73b2db9.gif)

**Comment by fanhexin** [comment]
虽然有下载按钮，但是下载按钮上不一定有下载链接的，可能通过js做了些事，总之那个按钮上应该没有链接，不是一个a标签。你可以调出来浏览器调试工具就知道了。另外你自己填在文本框里的字符串链接插件是不识别的，它只识别网页中的超链接。如果插件成功添加了链接到离线下载，会有个成功的提示，没有提示一般就没成功。我这里应该添加些对异常情况的反馈给你就好了，之后我有时间加上。
